/*
 This include is scipted or made by Bo$$.
 */




#define DWhite "{FFFFFF}"
#define DRed "{F81414}" 
#define TGrey  0xAFAFAFAA
#define TGreen  0x33AA33AA
#define TYellow 0xFFFF00AA
#define TBlue 0x0000BBAA
#define TLBlue 0x33CCFFAA
#define TOrange 0xFF9900AA
#define TRed 0xAA3333AA
#define TLime 0x10F441AA
#define TMagenta 0xFF00FFFF
#define TNavy 0x000080AA
#define TAqua 0xF0F8FFAA
#define COL_WHITE  			"{FFFFFF}"//boss
#define COL_RED    			"{F81414}"
#define COL_GREEN 			"{00FF22}"
#define COL_LIGHTBLUE 		"{00CED1}"
#define COLOR_RED 			0xFF0000FF
#define COLOR_ORANGE 		0xFF9900AA
#define COLOR_GREY 			0xC0C0C0FF // Defining the color 'Grey'
#define COLOR_WHITE 		0xFFFFFFAA
#define COLOR_LIME 			0x10F441AA
#define COLOR_MAGNETA 		0xFF00FFFF
#define COLOR_NAVY 			0x000080AA				
//#define COLOR_GREY 			0xAFAFAFAA
#define COLOR_GREEN         0x33AA33AA
#define COLOR_YELLOW 		0xFFFF00AA
#define COLOR_WHITE 		0xFFFFFFAA
#define COLOR_BLUE 			0x0000BBAA
#define COLOR_LIGHTBLUE 	0x33CCFFAA
#define COLOR_ORANGE 		0xFF9900AA
#define COLOR_LIME			0x10F441AA
#define COLOR_MAGENTA 		0xFF00FFFF
#define COLOR_NAVY 			0x000080AA
#define COLOR_AQUA 			0xF0F8FFAA
#define COLOR_CRIMSON 		0xDC143CAA
#define COLOR_FLBLUE 		0x6495EDAA
#define COLOR_BISQUE 		0xFFE4C4AA
#define COLOR_BLACK 		0x000000AA
#define COLOR_CHARTREUSE 	0x7FFF00AA
#define COLOR_BROWN 		0XA52A2AAA
#define COLOR_CORAL 		0xFF7F50AA
#define COLOR_GOLD 			0xB8860BAA
#define COLOR_GREENYELLOW 	0xADFF2FAA
#define COLOR_INDIGO 		0x4B00B0AA
#define COLOR_IVORY 		0xFFFF82AA
#define COLOR_LAWNGREEN		0x7CFC00AA
#define COLOR_SEAGREEN 		0x20B2AAAA
#define COLOR_LIMEGREEN 	0x32CD32AA //<--- Dark lime
#define COLOR_MIDNIGHTBLUE 	0X191970AA
#define COLOR_MAROON		0x800000AA
#define COLOR_OLIVE 		0x808000AA
#define COLOR_ORANGERED 	0xFF4500AA
#define COLOR_PINK 			0xFFC0CBAA // - Light light pink
#define COLOR_SPRINGGREEN 	0x00FF7FAA
#define COLOR_TOMATO 		0xFF6347AA // - Tomato >:/ sounds wrong lol... well... :P
#define COLOR_YELLOWGREEN 	0x9ACD32AA //- like military green
#define COLOR_MEDIUMAQUA 	0x83BFBFAA
#define COLOR_MEDIUMMAGENTA 0x8B008BAA // dark magenta ^

